### ISSUE TITLE
How to provide probabilities as well for pairwise to list ?

### ISSUE THREAD

**Issue by g-hrafiq** [lucasmaystre/choix#6]
Hi Author,

I came down to this library from the Stackoverflow question that you have answered at https://datascience.stackexchange.com/questions/18828/from-pairwise-comparisons-to-ranking-python .

I have probabilities for each pairwise comparison, can that also go as input to any of the lsr_pairwise / ilsr_pairwise methods ? Example, let's say probabilities coming from a pairwise classifier trained separately.

Thanks,
Hasan

**Comment by lucasmaystre** [comment]
Hi @g-hrafiq , I think you could use the method [`ilsr_pairwise_dense`](http://choix.lum.li/en/latest/api.html#choix.ilsr_pairwise_dense) for this. I haven't tested it, but I think it should work if you pass it a matrix of probabilities (i.e. "counts" between 0 and 1).

Hope it helps. Let me know otherwise!
